import Foundation

struct ChronologyEvent: Identifiable {
    var id = UUID()
    var description: String
    var year: Int
    var details: String
}

let allEvents: [ChronologyEvent] = [
    ChronologyEvent(description: "Signing of the Declaration of Independence", year: 1776, details: "The Declaration of Independence was adopted by the Continental Congress on July 4, 1776. It declared the thirteen American colonies independent from British rule."),
    ChronologyEvent(description: "First Moon Landing", year: 1969, details: "On July 20, 1969, Apollo 11's lunar module, the Eagle, landed on the Moon, marking the first time humans set foot on another celestial body."),
    ChronologyEvent(description: "Fall of the Berlin Wall", year: 1989, details: "The Berlin Wall, a symbol of the Cold War, fell on November 9, 1989, leading to the reunification of East and West Germany."),
    ChronologyEvent(description: "Invention of the Printing Press", year: 1440, details: "Johannes Gutenberg invented the printing press around 1440. This invention revolutionized the way information was disseminated and books were produced."),
    ChronologyEvent(description: "Discovery of Penicillin", year: 1928, details: "Alexander Fleming discovered penicillin in 1928. This antibiotic revolutionized medicine and saved countless lives."),
    ChronologyEvent(description: "End of World War II", year: 1945, details: "World War II ended in 1945 with the surrender of Germany in May and Japan in September, marking the end of the deadliest conflict in human history."),
    ChronologyEvent(description: "Assassination of Archduke Franz Ferdinand", year: 1914, details: "The assassination of Archduke Franz Ferdinand of Austria on June 28, 1914, led to the outbreak of World War I."),
    ChronologyEvent(description: "Wright Brothers' First Flight", year: 1903, details: "Orville and Wilbur Wright made the first successful powered flight on December 17, 1903, at Kitty Hawk, North Carolina."),
    ChronologyEvent(description: "Stock Market Crash", year: 1929, details: "The stock market crash of October 29, 1929, known as Black Tuesday, marked the beginning of the Great Depression."),
    ChronologyEvent(description: "Civil Rights Act", year: 1964, details: "The Civil Rights Act of 1964 was a landmark piece of legislation in the United States that outlawed discrimination based on race, color, religion, sex, or national origin."),
    ChronologyEvent(description: "Formation of the United Nations", year: 1945, details: "The United Nations was founded on October 24, 1945, to promote international cooperation and prevent future conflicts."),
    ChronologyEvent(description: "Sinking of the Titanic", year: 1912, details: "The RMS Titanic sank on April 15, 1912, after hitting an iceberg during its maiden voyage, resulting in the deaths of more than 1,500 passengers and crew."),
    ChronologyEvent(description: "Women's Suffrage", year: 1920, details: "The 19th Amendment to the U.S. Constitution was ratified on August 18, 1920, granting women the right to vote."),
    ChronologyEvent(description: "Invention of the Telephone", year: 1876, details: "Alexander Graham Bell was awarded the first U.S. patent for the invention of the telephone on March 7, 1876."),
    ChronologyEvent(description: "Attack on Pearl Harbor", year: 1941, details: "The attack on Pearl Harbor by the Japanese Navy on December 7, 1941, led the United States to enter World War II."),
    ChronologyEvent(description: "Fall of Constantinople", year: 1453, details: "The Fall of Constantinople to the Ottoman Empire on May 29, 1453, marked the end of the Byzantine Empire and a significant shift in the balance of power in Europe."),
    ChronologyEvent(description: "Signing of the Magna Carta", year: 1215, details: "The Magna Carta, signed by King John of England in 1215, is considered one of the foundational documents of modern democracy."),
    ChronologyEvent(description: "First Battle of Bull Run", year: 1861, details: "The First Battle of Bull Run, fought on July 21, 1861, was the first major battle of the American Civil War."),
    ChronologyEvent(description: "Discovery of America", year: 1492, details: "Christopher Columbus discovered the Americas on October 12, 1492, while seeking a new route to the East Indies."),
    ChronologyEvent(description: "Martin Luther's Ninety-Five Theses", year: 1517, details: "Martin Luther nailed his Ninety-Five Theses to the door of the Castle Church in Wittenberg on October 31, 1517, sparking the Protestant Reformation."),
    ChronologyEvent(description: "Great Fire of London", year: 1666, details: "The Great Fire of London destroyed much of the city in September 1666, leading to a major rebuilding effort."),
    ChronologyEvent(description: "Boston Tea Party", year: 1773, details: "The Boston Tea Party, a political protest by the Sons of Liberty on December 16, 1773, was a key event leading up to the American Revolution."),
    ChronologyEvent(description: "French Revolution Begins", year: 1789, details: "The French Revolution began in 1789, leading to the overthrow of the monarchy and the rise of the French Republic."),
    ChronologyEvent(description: "Louisiana Purchase", year: 1803, details: "The Louisiana Purchase, made by the United States from France in 1803, doubled the size of the country."),
    ChronologyEvent(description: "Battle of Waterloo", year: 1815, details: "The Battle of Waterloo, fought on June 18, 1815, marked the final defeat of Napoleon Bonaparte."),
    ChronologyEvent(description: "The War of 1812", year: 1812, details: "The War of 1812 was fought between the United States and Great Britain from 1812 to 1815, ending in a stalemate."),
    ChronologyEvent(description: "Missouri Compromise", year: 1820, details: "The Missouri Compromise, passed in 1820, was a key piece of legislation in the early history of the United States regarding the expansion of slavery."),
    ChronologyEvent(description: "Trail of Tears", year: 1838, details: "The Trail of Tears refers to the forced relocation of Native American nations from their ancestral homelands in the Southeastern United States to an area west of the Mississippi River."),
    ChronologyEvent(description: "Gold Rush in California", year: 1849, details: "The California Gold Rush began in 1849, leading to a massive influx of settlers and the rapid growth of California."),
    ChronologyEvent(description: "Emancipation Proclamation", year: 1863, details: "President Abraham Lincoln issued the Emancipation Proclamation on January 1, 1863, declaring all slaves in Confederate territory free."),
    ChronologyEvent(description: "Assassination of Abraham Lincoln", year: 1865, details: "President Abraham Lincoln was assassinated by John Wilkes Booth on April 14, 1865, just days after the end of the Civil War."),
    ChronologyEvent(description: "Completion of the Transcontinental Railroad", year: 1869, details: "The First Transcontinental Railroad was completed on May 10, 1869, linking the eastern and western United States."),
    ChronologyEvent(description: "Battle of Little Bighorn", year: 1876, details: "The Battle of Little Bighorn, also known as Custer's Last Stand, was fought on June 25-26, 1876, between the U.S. Army and Native American tribes."),
    ChronologyEvent(description: "Edison's First Light Bulb", year: 1879, details: "Thomas Edison successfully tested his first practical incandescent light bulb on October 22, 1879."),
    ChronologyEvent(description: "Formation of the National Parks Service", year: 1916, details: "The National Park Service was established on August 25, 1916, to manage and preserve national parks and monuments in the United States."),
    ChronologyEvent(description: "Women Win the Right to Vote", year: 1920, details: "The 19th Amendment to the U.S. Constitution was ratified on August 18, 1920, granting women the right to vote."),
    ChronologyEvent(description: "The Great Depression Begins", year: 1929, details: "The stock market crash of October 29, 1929, marked the beginning of the Great Depression."),
    ChronologyEvent(description: "D-Day Invasion", year: 1944, details: "The D-Day invasion of Normandy took place on June 6, 1944, and was a turning point in World War II."),
    ChronologyEvent(description: "First Man in Space", year: 1961, details: "Yuri Gagarin became the first human to travel into space on April 12, 1961."),
    ChronologyEvent(description: "Cuban Missile Crisis", year: 1962, details: "The Cuban Missile Crisis of October 1962 was a 13-day confrontation between the United States and the Soviet Union over Soviet ballistic missiles deployed in Cuba."),
    ChronologyEvent(description: "Watergate Scandal", year: 1972, details: "The Watergate scandal led to the resignation of President Richard Nixon in 1974."),
    ChronologyEvent(description: "Fall of Saigon", year: 1975, details: "The Fall of Saigon on April 30, 1975, marked the end of the Vietnam War."),
    ChronologyEvent(description: "The Internet is Born", year: 1983, details: "The ARPANET officially adopted the TCP/IP protocol on January 1, 1983, leading to the creation of the modern Internet."),
    ChronologyEvent(description: "Chernobyl Disaster", year: 1986, details: "The Chernobyl disaster, a catastrophic nuclear accident, occurred on April 26, 1986."),
    ChronologyEvent(description: "Nelson Mandela Released from Prison", year: 1990, details: "Nelson Mandela was released from prison on February 11, 1990, after 27 years of incarceration."),
    ChronologyEvent(description: "Fall of the Soviet Union", year: 1991, details: "The Soviet Union officially dissolved on December 26, 1991, ending the Cold War."),
    ChronologyEvent(description: "9/11 Terrorist Attacks", year: 2001, details: "The terrorist attacks of September 11, 2001, resulted in the destruction of the World Trade Center and significant loss of life."),
    ChronologyEvent(description: "Hurricane Katrina", year: 2005, details: "Hurricane Katrina struck the Gulf Coast on August 29, 2005, causing widespread devastation, particularly in New Orleans."),
    ChronologyEvent(description: "Election of Barack Obama", year: 2008, details: "Barack Obama was elected as the first African American President of the United States in November 2008."),
    ChronologyEvent(description: "Arab Spring", year: 2010, details: "The Arab Spring was a series of anti-government protests and uprisings that spread across the Arab world beginning in late 2010."),
    ChronologyEvent(description: "Fukushima Nuclear Disaster", year: 2011, details: "The Fukushima Daiichi nuclear disaster was triggered by a tsunami following an earthquake on March 11, 2011."),
    ChronologyEvent(description: "Brexit Referendum", year: 2016, details: "The United Kingdom voted to leave the European Union in a referendum held on June 23, 2016."),
    ChronologyEvent(description: "COVID-19 Pandemic", year: 2020, details: "The COVID-19 pandemic, caused by the novel coronavirus, led to a global health crisis beginning in early 2020."),
    ChronologyEvent(description: "Landing of Perseverance Rover on Mars", year: 2021, details: "NASA's Perseverance rover successfully landed on Mars on February 18, 2021, to search for signs of ancient life and collect samples."),
    ChronologyEvent(description: "War in Ukraine", year: 2022, details: "Russia invaded Ukraine on February 24, 2022, leading to a major conflict with significant global implications."),
    // Continue to add events until you reach 200
    ChronologyEvent(description: "Signing of the Paris Agreement", year: 2015, details: "The Paris Agreement, signed on December 12, 2015, is an international treaty aimed at combating climate change."),
    ChronologyEvent(description: "Invention of the World Wide Web", year: 1989, details: "Tim Berners-Lee invented the World Wide Web in 1989, revolutionizing how information is shared and accessed."),
    ChronologyEvent(description: "Launching of Hubble Space Telescope", year: 1990, details: "The Hubble Space Telescope was launched into low Earth orbit on April 24, 1990, providing unprecedented views of the universe."),
    ChronologyEvent(description: "End of Apartheid", year: 1994, details: "Apartheid, a system of institutionalized racial segregation, ended in South Africa with the election of Nelson Mandela as president in 1994."),
    ChronologyEvent(description: "Discovery of DNA Structure", year: 1953, details: "James Watson and Francis Crick discovered the double helix structure of DNA in 1953, leading to significant advancements in genetics."),
    ChronologyEvent(description: "Launch of Sputnik", year: 1957, details: "Sputnik, the first artificial satellite, was launched by the Soviet Union on October 4, 1957, marking the beginning of the space age."),
    ChronologyEvent(description: "Mahatma Gandhi's Assassination", year: 1948, details: "Mahatma Gandhi, leader of the Indian independence movement, was assassinated on January 30, 1948."),
    ChronologyEvent(description: "End of the Cold War", year: 1991, details: "The Cold War, a period of geopolitical tension between the Soviet Union and the United States, ended with the dissolution of the Soviet Union in 1991."),
    ChronologyEvent(description: "First Human Heart Transplant", year: 1967, details: "The first successful human heart transplant was performed by Dr. Christiaan Barnard on December 3, 1967, in South Africa."),
    ChronologyEvent(description: "Tiananmen Square Massacre", year: 1989, details: "The Tiananmen Square Massacre occurred on June 4, 1989, when the Chinese government violently suppressed pro-democracy protesters."),
    ChronologyEvent(description: "Discovery of the Electron", year: 1897, details: "J.J. Thomson discovered the electron in 1897, leading to the development of modern atomic theory."),
    ChronologyEvent(description: "Assassination of John F. Kennedy", year: 1963, details: "President John F. Kennedy was assassinated in Dallas, Texas, on November 22, 1963."),
    ChronologyEvent(description: "Formation of NATO", year: 1949, details: "The North Atlantic Treaty Organization (NATO) was formed on April 4, 1949, as a military alliance between North American and European countries."),
    ChronologyEvent(description: "Dissolution of the Soviet Union", year: 1991, details: "The Soviet Union was officially dissolved on December 26, 1991, marking the end of the Cold War."),
    ChronologyEvent(description: "Launch of the International Space Station", year: 1998, details: "The first module of the International Space Station was launched on November 20, 1998, marking the beginning of an international collaborative space project."),
    ChronologyEvent(description: "Hiroshima and Nagasaki Bombings", year: 1945, details: "The United States dropped atomic bombs on Hiroshima and Nagasaki in Japan on August 6 and 9, 1945, leading to Japan's surrender in World War II."),
    ChronologyEvent(description: "Formation of the European Union", year: 1993, details: "The European Union was established on November 1, 1993, with the signing of the Maastricht Treaty."),
    ChronologyEvent(description: "The Great Chicago Fire", year: 1871, details: "The Great Chicago Fire of October 8-10, 1871, destroyed much of the city and led to significant rebuilding efforts."),
    ChronologyEvent(description: "Assassination of Martin Luther King Jr.", year: 1968, details: "Civil rights leader Martin Luther King Jr. was assassinated on April 4, 1968, in Memphis, Tennessee."),
    ChronologyEvent(description: "End of Prohibition", year: 1933, details: "Prohibition in the United States ended on December 5, 1933, with the ratification of the 21st Amendment."),
    ChronologyEvent(description: "Wright Brothers' First Flight", year: 1903, details: "Orville and Wilbur Wright made the first successful powered flight on December 17, 1903, at Kitty Hawk, North Carolina."),
    ChronologyEvent(description: "Invention of the Radio", year: 1895, details: "Guglielmo Marconi is credited with inventing the radio in 1895, revolutionizing communication."),
    ChronologyEvent(description: "First Successful Organ Transplant", year: 1954, details: "The first successful organ transplant, a kidney transplant, was performed by Dr. Joseph Murray on December 23, 1954."),
    ChronologyEvent(description: "Discovery of Insulin", year: 1921, details: "Insulin was discovered by Frederick Banting and Charles Best in 1921, revolutionizing the treatment of diabetes."),
    ChronologyEvent(description: "Launch of Apollo 13", year: 1970, details: "Apollo 13, a NASA lunar mission, was launched on April 11, 1970. It famously experienced a critical failure but safely returned its crew to Earth."),
    ChronologyEvent(description: "First Artificial Heart Transplant", year: 1982, details: "The first successful implantation of a permanent artificial heart, the Jarvik-7, was performed on December 2, 1982."),
    ChronologyEvent(description: "Construction of the Panama Canal", year: 1914, details: "The Panama Canal was officially opened on August 15, 1914, connecting the Atlantic and Pacific Oceans."),
    ChronologyEvent(description: "First Televised Presidential Debate", year: 1960, details: "The first televised presidential debate in the United States was held on September 26, 1960, between John F. Kennedy and Richard Nixon."),
    ChronologyEvent(description: "First Successful Cloning of a Mammal", year: 1996, details: "Dolly the sheep, the first mammal to be cloned from an adult somatic cell, was born on July 5, 1996."),
    ChronologyEvent(description: "Start of the Korean War", year: 1950, details: "The Korean War began on June 25, 1950, when North Korea invaded South Korea."),
    ChronologyEvent(description: "Signing of the Treaty of Versailles", year: 1919, details: "The Treaty of Versailles, signed on June 28, 1919, officially ended World War I."),
    ChronologyEvent(description: "Discovery of the North Pole", year: 1909, details: "Robert Peary and his team are credited with reaching the North Pole on April 6, 1909."),
    ChronologyEvent(description: "Sinking of the Lusitania", year: 1915, details: "The RMS Lusitania was sunk by a German U-boat on May 7, 1915, contributing to the United States' entry into World War I."),
    ChronologyEvent(description: "Formation of the League of Nations", year: 1920, details: "The League of Nations was founded on January 10, 1920, as an international organization to promote peace and cooperation."),
    ChronologyEvent(description: "Launch of Sputnik 1", year: 1957, details: "Sputnik 1, the first artificial Earth satellite, was launched by the Soviet Union on October 4, 1957."),
    ChronologyEvent(description: "First Test of the Hydrogen Bomb", year: 1952, details: "The first successful test of a hydrogen bomb by the United States took place on November 1, 1952."),
    ChronologyEvent(description: "First Solo Non-stop Transatlantic Flight", year: 1927, details: "Charles Lindbergh completed the first solo non-stop transatlantic flight on May 20-21, 1927."),
    ChronologyEvent(description: "First Talking Motion Picture", year: 1927, details: "The first talking motion picture, 'The Jazz Singer,' was released on October 6, 1927."),
    ChronologyEvent(description: "Discovery of Pluto", year: 1930, details: "Clyde Tombaugh discovered Pluto on February 18, 1930, at the Lowell Observatory."),
    ChronologyEvent(description: "Start of the Great Depression", year: 1929, details: "The stock market crash of October 29, 1929, marked the beginning of the Great Depression."),
    ChronologyEvent(description: "First Atomic Bomb Test", year: 1945, details: "The first test of an atomic bomb, known as the Trinity test, was conducted by the United States on July 16, 1945."),
    ChronologyEvent(description: "Signing of the Civil Rights Act", year: 1964, details: "The Civil Rights Act of 1964 was signed into law by President Lyndon B. Johnson on July 2, 1964."),
    ChronologyEvent(description: "Formation of the United Nations", year: 1945, details: "The United Nations was founded on October 24, 1945, to promote international cooperation and peace."),
    ChronologyEvent(description: "Assassination of Robert F. Kennedy", year: 1968, details: "Senator Robert F. Kennedy was assassinated on June 5, 1968, in Los Angeles, California."),
    ChronologyEvent(description: "First Color Television Broadcast", year: 1954, details: "The first national color television broadcast in the United States was aired on January 1, 1954."),
    ChronologyEvent(description: "Signing of the Helsinki Accords", year: 1975, details: "The Helsinki Accords, signed on August 1, 1975, were an agreement to improve relations between the Communist bloc and the West."),
    ChronologyEvent(description: "Launch of the Space Shuttle", year: 1981, details: "The first space shuttle, Columbia, was launched on April 12, 1981."),
    ChronologyEvent(description: "First Non-stop Flight Around the World", year: 1986, details: "The Voyager aircraft completed the first non-stop, unrefueled flight around the world on December 23, 1986."),
    ChronologyEvent(description: "Signing of the Camp David Accords", year: 1978, details: "The Camp David Accords, signed on September 17, 1978, led to a peace treaty between Israel and Egypt."),
    ChronologyEvent(description: "Start of the Iraq War", year: 2003, details: "The Iraq War began on March 20, 2003, with the invasion of Iraq by the United States and its allies."),
    ChronologyEvent(description: "First Flight of the Concorde", year: 1969, details: "The first flight of the Concorde, a supersonic passenger jet, took place on March 2, 1969."),
    ChronologyEvent(description: "First Woman in Space", year: 1963, details: "Valentina Tereshkova became the first woman to travel into space on June 16, 1963."),
    ChronologyEvent(description: "Discovery of the Structure of DNA", year: 1953, details: "James Watson and Francis Crick discovered the double helix structure of DNA in 1953."),
    ChronologyEvent(description: "Establishment of the World Health Organization", year: 1948, details: "The World Health Organization (WHO) was established on April 7, 1948, as a specialized agency of the United Nations."),
    ChronologyEvent(description: "First Successful Kidney Transplant", year: 1954, details: "The first successful kidney transplant was performed by Dr. Joseph Murray on December 23, 1954."),
    ChronologyEvent(description: "Discovery of Penicillin", year: 1928, details: "Alexander Fleming discovered penicillin in 1928, revolutionizing the treatment of bacterial infections."),
    ChronologyEvent(description: "First Woman to Climb Mount Everest", year: 1975, details: "Junko Tabei became the first woman to reach the summit of Mount Everest on May 16, 1975."),
    ChronologyEvent(description: "Introduction of the Euro", year: 1999, details: "The Euro became the official currency of the Eurozone on January 1, 1999."),
    ChronologyEvent(description: "First Black President of South Africa", year: 1994, details: "Nelson Mandela was elected as the first black president of South Africa on May 10, 1994."),
    ChronologyEvent(description: "End of World War I", year: 1918, details: "World War I ended on November 11, 1918, with the signing of the armistice."),
    ChronologyEvent(description: "Birth of the United Nations", year: 1945, details: "The United Nations was established on October 24, 1945, to promote peace and cooperation among nations."),
    ChronologyEvent(description: "Formation of NATO", year: 1949, details: "The North Atlantic Treaty Organization (NATO) was formed on April 4, 1949, as a military alliance between North American and European countries."),
    ChronologyEvent(description: "First Human Heart Transplant", year: 1967, details: "The first successful human heart transplant was performed by Dr. Christiaan Barnard on December 3, 1967."),
    ChronologyEvent(description: "Launch of Sputnik 1", year: 1957, details: "Sputnik 1, the first artificial Earth satellite, was launched by the Soviet Union on October 4, 1957."),
    ChronologyEvent(description: "First Solo Non-stop Transatlantic Flight", year: 1927, details: "Charles Lindbergh completed the first solo non-stop transatlantic flight on May 20-21, 1927."),
    ChronologyEvent(description: "First Successful Cloning of a Mammal", year: 1996, details: "Dolly the sheep, the first mammal to be cloned from an adult somatic cell, was born on July 5, 1996."),
    ChronologyEvent(description: "Start of the Korean War", year: 1950, details: "The Korean War began on June 25, 1950, when North Korea invaded South Korea."),
    ChronologyEvent(description: "Signing of the Treaty of Versailles", year: 1919, details: "The Treaty of Versailles, signed on June 28, 1919, officially ended World War I."),
    ChronologyEvent(description: "Discovery of the North Pole", year: 1909, details: "Robert Peary and his team are credited with reaching the North Pole on April 6, 1909."),
    ChronologyEvent(description: "Sinking of the Lusitania", year: 1915, details: "The RMS Lusitania was sunk by a German U-boat on May 7, 1915, contributing to the United States' entry into World War I."),
    ChronologyEvent(description: "Formation of the League of Nations", year: 1920, details: "The League of Nations was founded on January 10, 1920, as an international organization to promote peace and cooperation.")
]
